### ISSUE TITLE
 About Temporal Consistency Graph Module 

### ISSUE THREAD

**Issue by poweryin** [jx-zhong-for-academic-purpose/GCN-Anomaly-Detection#3]
Hi,I am interested in the paper.I have two questions after reading the article.
1) In the Temporal Consistency Graph Module, I want to know what form i and j are represented in the formula. Why do you choose to use Laplacian kernel ? The article only says that i represents the i-th snippet.
2)  input a V(Anomaly Videos snippets contain N snippets) into the action  classifier , the i and j snippet in the V must be from the same video, or can come from different videos?

looking forward to your reply，thanks

**Comment by jx-zhong-for-academic-purpose** [comment]
Thanks for your interest.
1. The "i" or "j" is the ordinal number of the corresponding snippet. For example, if we extract the feature sample every 5 frames, the "i" of the 6th-10th frames is 2. 
Laplacian kernel is a type of exponential kernels, and we choose it because it works better than other kernels in the preliminary experiment. The reason may be the exponential function can "amplify" the distinction of various temporal distances.
2. In our paper, the snippets are viewed as vertexes and a video is considered as a graph. The snippets within the same graph are naturally from the same video. To enable them from different videos is a promising direction, but it seems out of my league as it is hard to deal with the temporal relationship over different videos.

**Comment by poweryin** [comment]
Thank you,I get it
